# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

$:.unshift File.expand_path('lib', File.dirname(__FILE__))
require 'openstack/version'

Gem::Specification.new do |s|
  s.name = "openstack"
  s.version = OpenStack::VERSION

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dan Prince", "Marios Andreou"]
  s.date = "2013-07-09"
  s.description = "API Binding for OpenStack"
  s.email = ["dprince@redhat.com", "marios@redhat.com"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [ "COPYING", "README.rdoc" ] + Dir["lib/*.rb"] + Dir["lib/*/*.rb"] + Dir["lib/*/*/*.rb"] + Dir["test/*.rb"]
  
  s.homepage = "https://github.com/ruby-openstack/ruby-openstack"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "OpenStack Ruby API"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency('mocha')
      s.add_development_dependency('rake')
      s.add_development_dependency('test-unit')
      s.add_runtime_dependency('json')
    else
      s.add_dependency('mocha')
      s.add_dependency('test-unit')
      s.add_dependency('json')
    end
  else
    s.add_dependency('mocha')
    s.add_dependency('test-unit')
    s.add_dependency('json')
  end
end

